version: "3"
services:
  web:
    build: .
    container_name: rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production"
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    environment:
      - RAILS_SERVE_STATIC_FILES=true
