name: rails-doc

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master, dev]

jobs:
  compose-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: up
        run: docker-compose up -d
      - name: down
        run: docker-compose down

  deploy:
    needs: [compose-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: echo "$PRIVATE_KEY" > private_key && chmod 600 private_key &&
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} 'cd /var/www/aws-laravel/ && git pull origin master && make restart'
