name: rails-doc

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master, dev]

jobs:
  compose-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: up
        run: docker-compose up -d
      - name: down
        run: docker-compose down

  deploy:
    needs: [compose-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ssh settings
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: touch ~/.ssh/private_key.pem && echo "$PRIVATE_KEY" > ~/.ssh/private_key.pem && chmod 600 ~/.ssh/private_key.pem
      - name: Deploy
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ${USER_NAME}@${HOST_NAME} 'cd ~/app/api_collection && git pull origin master && make restart'
