name: rails-doc

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ssh settings
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      - name: Deploy
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} 'cd ~/app/api_collection && git pull origin master && make restart'
